# Generated by Django 5.2 on 2025-05-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0002_folderentry_fileentry_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_email',
            field=models.EmailField(blank=True, help_text='Your personal Google email to share files with', max_length=254, null=True),
        ),
    ]
